@startuml diagrama
class PatrullaEspiritual
class TazoDorado{
    - Bool flotando
    +Flotar()
}
class Anexo
class GranLider
class Foco
PatrullaEspiritual o-- TazoDorado
GranLider"1" *-- "*"Foco
TazoDorado"1" o-- "*"Foco
TazoDorado *-- EstadoFlotacion
@enduml